// Extended element data: shell distributions, crystal structures, applications, facts.
// Shell counts follow the Bohr model (electrons per principal quantum shell K–Q).

export const SHELL_DISTRIBUTIONS: Record<number, number[]> = {
  1:   [1],
  2:   [2],
  3:   [2,1],
  4:   [2,2],
  5:   [2,3],
  6:   [2,4],
  7:   [2,5],
  8:   [2,6],
  9:   [2,7],
  10:  [2,8],
  11:  [2,8,1],
  12:  [2,8,2],
  13:  [2,8,3],
  14:  [2,8,4],
  15:  [2,8,5],
  16:  [2,8,6],
  17:  [2,8,7],
  18:  [2,8,8],
  19:  [2,8,8,1],
  20:  [2,8,8,2],
  21:  [2,8,9,2],
  22:  [2,8,10,2],
  23:  [2,8,11,2],
  24:  [2,8,13,1],
  25:  [2,8,13,2],
  26:  [2,8,14,2],
  27:  [2,8,15,2],
  28:  [2,8,16,2],
  29:  [2,8,18,1],
  30:  [2,8,18,2],
  31:  [2,8,18,3],
  32:  [2,8,18,4],
  33:  [2,8,18,5],
  34:  [2,8,18,6],
  35:  [2,8,18,7],
  36:  [2,8,18,8],
  37:  [2,8,18,8,1],
  38:  [2,8,18,8,2],
  39:  [2,8,18,9,2],
  40:  [2,8,18,10,2],
  41:  [2,8,18,12,1],
  42:  [2,8,18,13,1],
  43:  [2,8,18,13,2],
  44:  [2,8,18,15,1],
  45:  [2,8,18,16,1],
  46:  [2,8,18,18],
  47:  [2,8,18,18,1],
  48:  [2,8,18,18,2],
  49:  [2,8,18,18,3],
  50:  [2,8,18,18,4],
  51:  [2,8,18,18,5],
  52:  [2,8,18,18,6],
  53:  [2,8,18,18,7],
  54:  [2,8,18,18,8],
  55:  [2,8,18,18,8,1],
  56:  [2,8,18,18,8,2],
  57:  [2,8,18,18,9,2],
  58:  [2,8,18,19,9,2],
  59:  [2,8,18,21,8,2],
  60:  [2,8,18,22,8,2],
  61:  [2,8,18,23,8,2],
  62:  [2,8,18,24,8,2],
  63:  [2,8,18,25,8,2],
  64:  [2,8,18,25,9,2],
  65:  [2,8,18,27,8,2],
  66:  [2,8,18,28,8,2],
  67:  [2,8,18,29,8,2],
  68:  [2,8,18,30,8,2],
  69:  [2,8,18,31,8,2],
  70:  [2,8,18,32,8,2],
  71:  [2,8,18,32,9,2],
  72:  [2,8,18,32,10,2],
  73:  [2,8,18,32,11,2],
  74:  [2,8,18,32,12,2],
  75:  [2,8,18,32,13,2],
  76:  [2,8,18,32,14,2],
  77:  [2,8,18,32,15,2],
  78:  [2,8,18,32,17,1],
  79:  [2,8,18,32,18,1],
  80:  [2,8,18,32,18,2],
  81:  [2,8,18,32,18,3],
  82:  [2,8,18,32,18,4],
  83:  [2,8,18,32,18,5],
  84:  [2,8,18,32,18,6],
  85:  [2,8,18,32,18,7],
  86:  [2,8,18,32,18,8],
  87:  [2,8,18,32,18,8,1],
  88:  [2,8,18,32,18,8,2],
  89:  [2,8,18,32,18,9,2],
  90:  [2,8,18,32,18,10,2],
  91:  [2,8,18,32,20,9,2],
  92:  [2,8,18,32,21,9,2],
  93:  [2,8,18,32,22,9,2],
  94:  [2,8,18,32,24,8,2],
  95:  [2,8,18,32,25,8,2],
  96:  [2,8,18,32,25,9,2],
  97:  [2,8,18,32,27,8,2],
  98:  [2,8,18,32,28,8,2],
  99:  [2,8,18,32,29,8,2],
  100: [2,8,18,32,30,8,2],
  101: [2,8,18,32,31,8,2],
  102: [2,8,18,32,32,8,2],
  103: [2,8,18,32,32,8,3],
  104: [2,8,18,32,32,10,2],
  105: [2,8,18,32,32,11,2],
  106: [2,8,18,32,32,12,2],
  107: [2,8,18,32,32,13,2],
  108: [2,8,18,32,32,14,2],
  109: [2,8,18,32,32,15,2],
  110: [2,8,18,32,32,17,1],
  111: [2,8,18,32,32,18,1],
  112: [2,8,18,32,32,18,2],
  113: [2,8,18,32,32,18,3],
  114: [2,8,18,32,32,18,4],
  115: [2,8,18,32,32,18,5],
  116: [2,8,18,32,32,18,6],
  117: [2,8,18,32,32,18,7],
  118: [2,8,18,32,32,18,8],
};

// Maps atomic number to crystal structure name.
// Structures shown in CrystalViz: "BCC" | "FCC" | "HCP" | "Diamond Cubic" | "Simple Cubic"
// Others rendered with label-only fallback.
export const CRYSTAL_STRUCTURES: Record<number, string> = {
  1:   "Hexagonal",
  2:   "FCC",
  3:   "BCC",
  4:   "HCP",
  5:   "Rhombohedral",
  6:   "Diamond Cubic",
  7:   "Hexagonal",
  8:   "Orthorhombic",
  9:   "Orthorhombic",
  10:  "FCC",
  11:  "BCC",
  12:  "HCP",
  13:  "FCC",
  14:  "Diamond Cubic",
  15:  "Orthorhombic",
  16:  "Orthorhombic",
  17:  "Orthorhombic",
  18:  "FCC",
  19:  "BCC",
  20:  "FCC",
  21:  "HCP",
  22:  "HCP",
  23:  "BCC",
  24:  "BCC",
  25:  "BCC",
  26:  "BCC",
  27:  "HCP",
  28:  "FCC",
  29:  "FCC",
  30:  "HCP",
  31:  "Orthorhombic",
  32:  "Diamond Cubic",
  33:  "Rhombohedral",
  34:  "Hexagonal",
  35:  "Orthorhombic",
  36:  "FCC",
  37:  "BCC",
  38:  "FCC",
  39:  "HCP",
  40:  "HCP",
  41:  "BCC",
  42:  "BCC",
  43:  "HCP",
  44:  "HCP",
  45:  "FCC",
  46:  "FCC",
  47:  "FCC",
  48:  "HCP",
  49:  "Tetragonal",
  50:  "Tetragonal",
  51:  "Rhombohedral",
  52:  "Hexagonal",
  53:  "Orthorhombic",
  54:  "FCC",
  55:  "BCC",
  56:  "BCC",
  57:  "HCP",
  58:  "FCC",
  59:  "HCP",
  60:  "HCP",
  61:  "HCP",
  62:  "Rhombohedral",
  63:  "BCC",
  64:  "HCP",
  65:  "HCP",
  66:  "HCP",
  67:  "HCP",
  68:  "HCP",
  69:  "HCP",
  70:  "FCC",
  71:  "HCP",
  72:  "HCP",
  73:  "BCC",
  74:  "BCC",
  75:  "HCP",
  76:  "HCP",
  77:  "FCC",
  78:  "FCC",
  79:  "FCC",
  80:  "Rhombohedral",
  81:  "HCP",
  82:  "FCC",
  83:  "Rhombohedral",
  84:  "Simple Cubic",
  85:  "Unknown",
  86:  "FCC",
  87:  "BCC",
  88:  "BCC",
  89:  "FCC",
  90:  "FCC",
  91:  "Tetragonal",
  92:  "Orthorhombic",
  93:  "Orthorhombic",
};

export const CRYSTAL_DESCRIPTIONS: Record<string, string> = {
  "BCC":          "Body-Centered Cubic — one atom at each corner and one at the cube center",
  "FCC":          "Face-Centered Cubic — atoms at corners and at the center of each face",
  "HCP":          "Hexagonal Close-Packed — alternating hexagonal layers for maximum packing",
  "Diamond Cubic":"Diamond Cubic — FCC lattice with 4 additional atoms in tetrahedral voids",
  "Simple Cubic": "Simple Cubic — atoms only at corners; found uniquely in polonium",
  "Hexagonal":    "Hexagonal — layered structure with 6-fold rotational symmetry",
  "Rhombohedral": "Rhombohedral — cube distorted along a body diagonal",
  "Tetragonal":   "Tetragonal — rectangular prism with two equal sides and one different",
  "Orthorhombic": "Orthorhombic — three mutually perpendicular axes of different lengths",
  "Unknown":      "Crystal structure not yet experimentally determined",
};

// Application data per element — each entry is a short label (used as title).
export const ELEMENT_APPLICATIONS: Record<number, string[]> = {
  1:  ["Fuel cells & clean energy", "Haber process for fertilisers", "Rocket propellant (liquid H₂)", "Hydrogenation of vegetable oils"],
  2:  ["MRI superconducting magnets", "Deep-sea diving gas mixtures", "Weather balloons & airships", "Cryogenic cooling near 0 K"],
  3:  ["Lithium-ion batteries (EVs)", "Psychiatric medicine (bipolar)", "Aerospace lightweight alloys", "Nuclear fusion tritium breeding"],
  4:  ["X-ray transmission windows", "Aerospace structural alloys", "Neutron reflector in reactors", "Gyroscope components"],
  5:  ["Borosilicate laboratory glass", "Semiconductor dopant", "Neutron absorber in reactors", "Insulation fibreglass"],
  6:  ["Steel & cast iron production", "Diamond cutting tools", "Graphite electrodes & pencils", "Carbon fibre composites"],
  7:  ["Ammonia (fertilisers, Haber)", "Explosives & propellants", "Food packaging (inert blanket)", "Cryogenic liquid nitrogen"],
  8:  ["Medical respiratory support", "Steelmaking (blast furnace)", "Water treatment", "Rocket oxidiser (liquid O₂)"],
  9:  ["Teflon (PTFE) non-stick coatings", "Fluoride in toothpaste", "Etching semiconductor wafers", "Refrigerants (HFCs)"],
  10: ["Neon advertising signs", "High-voltage indicator lamps", "Laser gain medium", "Cryogenic refrigeration"],
  11: ["Street lighting (sodium lamps)", "Table salt (NaCl) production", "Coolant in nuclear reactors", "Chemical reducing agent"],
  12: ["Lightweight aerospace alloys", "Chlorophyll (plant nutrition)", "Antacid medicines (MgO)", "Fireworks (bright white)"],
  13: ["Aircraft & vehicle bodywork", "Beverage cans & packaging", "High-voltage power lines", "Alloys with Cu (bronze-like)"],
  14: ["Microchip semiconductors", "Solar photovoltaic cells", "Optical fibres (silica)", "Construction glass & cement"],
  15: ["Agricultural fertilisers (NPK)", "Matches & pyrotechnics", "DNA, RNA & ATP (biology)", "Steel hardening additive"],
  16: ["Sulfuric acid (industry no. 1)", "Rubber vulcanisation", "Gunpowder & fireworks", "Fungicides & pesticides"],
  17: ["Municipal water purification", "PVC plastic production", "Bleach & disinfectants", "Pharmaceutical synthesis"],
  18: ["Welding shielding gas", "Incandescent light bulb fill", "Double-glazing window fill", "Plasma display panels"],
  19: ["Agricultural potash fertilisers", "Nerve signal transmission (K⁺)", "Glass & ceramics production", "Photography"],
  20: ["Structural bones & teeth (Ca²⁺)", "Portland cement (CaO)", "Antacids (calcium carbonate)", "Alloys & metallurgy"],
  22: ["Jet engine turbine blades", "Medical implants & prosthetics", "Sports equipment (Ti frames)", "Aerospace airframes"],
  23: ["Steel alloys (tool steel)", "Vanadium redox flow batteries", "Ceramics & glass colouring", "Aerospace castings"],
  24: ["Stainless steel (corrosion-free)", "Chrome plating & finishing", "Pigments (chrome yellow)", "Tanning leather"],
  25: ["Steel production (desulfuriser)", "Dry-cell batteries (MnO₂)", "Purple glass colouring", "Aluminium alloys"],
  26: ["Structural steel & cast iron", "Haemoglobin (oxygen carrier)", "Permanent magnets", "Catalysts (Haber process)"],
  27: ["High-speed tool steel alloys", "Rechargeable battery cathodes", "Jet engine superalloys", "Pigments (cobalt blue)"],
  28: ["Stainless steel alloying", "Electroplating (corrosion shield)", "Rechargeable Ni-MH batteries", "Coins & currency"],
  29: ["Electrical wiring & cables", "Plumbing pipes & fittings", "Heat exchangers", "Printed circuit boards"],
  30: ["Galvanised steel (rust-proof)", "Brass alloy (Cu + Zn)", "Zinc-oxide sunscreen", "Die-casting for auto parts"],
  32: ["Semiconductor devices", "Infrared optics & detectors", "Radar & fibre amplifiers", "Solar cells (thin film)"],
  35: ["Flame retardants (electronics)", "Photography (silver bromide)", "Fumigants & pesticides", "Medical sedatives (historic)"],
  47: ["Photography (film & print)", "Antimicrobial wound dressings", "Jewellery & silverware", "Electrical contacts (relays)"],
  50: ["Tin cans (food preservation)", "Solder (electronics)", "Bronze alloy (Cu + Sn)", "Organotin stabilisers (PVC)"],
  56: ["Barium X-ray contrast agent", "Vacuum tube getters", "Barium titanate (piezo)", "Fireworks (green colour)"],
  74: ["Tungsten-filament light bulbs", "Cutting tools (WC carbide)", "Radiation shielding", "Welding electrodes"],
  75: ["Jet engine turbine blades", "Platinum–rhenium catalysts", "Electrical contacts (switches)", "Thermocouple wires"],
  76: ["Hardest natural metal (alloys)", "Fountain pen tip alloys", "Catalysts in chemical synthesis", "Electrical contacts"],
  77: ["Spark plug electrodes", "Platinum alloys (hardener)", "Crucibles for high-temperature", "Catalytic converters"],
  78: ["Catalytic converters (cars)", "Laboratory crucibles & wires", "Jewellery & watches", "Fuel cell electrodes"],
  79: ["Monetary reserves & coinage", "Electronics (PCB contacts)", "Dental restorations", "Nanoparticle biosensors"],
  80: ["Fluorescent lamp ballasts", "Dental amalgam (historic)", "Scientific instruments (tilt)", "Gold extraction (amalgamation)"],
  82: ["Lead-acid batteries (cars)", "Radiation shielding (X-ray)", "Bullets & shot", "Solder (Pb-Sn, historic)"],
  92: ["Nuclear power reactor fuel", "Depleted U armour-piercing", "Radiation shielding (dense)", "Yellow glass pigment (historic)"],
};

export const ELEMENT_FACTS: Record<number, string> = {
  1:  "Hydrogen is the most abundant element in the universe, comprising about 75% of all normal matter by mass and powering stars via nuclear fusion.",
  2:  "Helium was discovered in the Sun's spectrum in 1868 — 27 years before it was found on Earth. Its name comes from 'Helios', the Greek sun god.",
  3:  "Lithium is light enough to float on water, yet reacts violently with it. Despite this, lithium salts have been used since the 1950s to treat bipolar disorder.",
  4:  "Beryllium is so stiff that a rod of it vibrates six times faster than an equivalent steel rod — making it prized for high-frequency speaker cones.",
  5:  "Boron does not exist in a pure elemental form in nature; it's always found as borates. Borax was used as a food preservative for centuries before its toxicity was recognised.",
  6:  "Carbon exists in forms with wildly different properties: diamond (hardest natural material) and graphite (so soft it writes on paper) are both pure carbon.",
  7:  "Despite nitrogen being essential to all life (it's in DNA and proteins), pure N₂ gas is so unreactive it was called 'azote' — French for 'without life'.",
  8:  "Oxygen was independently discovered by Carl Scheele (1772) and Joseph Priestley (1774), but it was Lavoisier who correctly identified it and named it.",
  9:  "Fluorine is so reactive it can set fire to glass, water, and even asbestos under the right conditions. It was so dangerous to isolate that several chemists died trying.",
  10: "Neon signs often don't contain neon. Only the orange-red glow is true neon; other colours use argon, mercury vapour, or phosphor coatings inside the tube.",
  11: "Sodium burns with a brilliant yellow flame so distinctive that sodium street lamps can be used to make the sky orange — helping astronomers reduce light pollution.",
  12: "Magnesium burns so intensely (at 3,100 °C) that it can continue burning in carbon dioxide and nitrogen — it cannot be extinguished by smothering.",
  13: "In the 1850s, aluminium was more precious than gold. Napoleon reserved aluminium cutlery for honoured guests while others ate with gold and silver utensils.",
  14: "Silicon makes up 28% of Earth's crust by mass and underpins modern civilisation through microchips — yet pure silicon was not isolated until 1824.",
  15: "Phosphorus was discovered in 1669 by Hennig Brand, who boiled down 50 buckets of urine hoping to find gold. Instead he found a glowing white waxy substance.",
  16: "Sulfur appears in the Bible as 'brimstone' and was used in warfare as 'Greek fire'. The distinctive smell of rotten eggs comes not from pure sulfur but from H₂S.",
  17: "Chlorine gas was the first large-scale chemical weapon, deployed by Germany at Ypres in April 1915. Its distinctive yellow-green colour and bleach smell made it recognisable.",
  18: "Argon makes up 0.93% of Earth's atmosphere — more than CO₂ — yet it wasn't discovered until 1894 because it forms no compounds and was invisible to early analysis.",
  19: "Potassium was the first metal ever isolated by electrolysis, achieved by Humphry Davy in 1807. It was named after 'pot ash' (wood ash dissolved in a pot).",
  20: "Your skeleton contains about 1 kg of calcium. Bone is constantly remodelled: virtually all calcium in your body is replaced roughly every 10 years.",
  22: "Titanium is as strong as steel but 45% lighter, and is completely corrosion-resistant. The SR-71 Blackbird spy plane was 93% titanium by weight.",
  26: "Iron meteorites found on Earth may be billions of years old and originate from destroyed planetary cores — ancient iron forged before our Solar System existed.",
  29: "Copper was the first metal humans learned to smelt, over 10,000 years ago. The Bronze Age began when copper was alloyed with tin to make a harder material.",
  30: "Zinc deficiency is a global health problem affecting over 2 billion people and causes stunted growth, impaired immunity, and delayed wound healing.",
  35: "Bromine is one of only two elements liquid at room temperature (the other is mercury). Its name comes from the Greek 'bromos' meaning 'stench of he-goats'.",
  47: "Silver has the highest electrical conductivity and thermal conductivity of any element. It also has the lowest contact resistance, making it ideal for precision switches.",
  50: "Tin has 10 stable isotopes — more than any other element. Below 13.2 °C, white tin transforms into crumbly grey 'tin pest', which reportedly doomed Napoleon's army.",
  74: "Tungsten has the highest melting point of any pure element (3,422 °C) and was used in light-bulb filaments because it can glow without melting.",
  75: "Rhenium is one of the rarest elements in Earth's crust — less than 1 ppb by mass. It was the last naturally-occurring element to be discovered, in 1925.",
  79: "All gold ever mined in human history — roughly 200,000 tonnes — would fit into a cube about 21 metres on each side, smaller than a tennis court.",
  80: "Mercury was once used in hat-making to process felt, causing neurological damage to hatters — the origin of the phrase 'mad as a hatter'.",
  82: "Lead's Latin name 'plumbum' gave English the words 'plumbing' and 'plumber', because Roman water pipes were made of lead — contributing to theories about Rome's fall.",
  92: "One kilogram of uranium-235 can release as much energy as burning 3,000 tonnes of coal. A single nuclear fuel pellet holds as much energy as 800 kg of coal.",
};
